### ISSUE TITLE
LICENSE is incorrect in recipe/meta.yml  (is GPLv3 should be Apachev2)

### ISSUE THREAD

**Issue by willprice** [sdvillal/lintel-feedstock#1]
lintel was re licensed from  GPLv3 to Apache v2 (see https://github.com/dukebw/lintel/blob/master/LICENSE)

**Comment by sdvillal** [comment]
Thanks. This package has been superseded by the one in conda-forge, that has proper license info. See: https://github.com/conda-forge/lintel-feedstock (install with ```conda install -c conda-forge lintel```).
